name: your_chef
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  google_sign_in: ^6.2.2
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/splash.png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/images/splash_android12.png
    color: "#ffffff"
    color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/dummy/categories/
    - assets/images/dummy/offers/
  fonts:
    - family: Vivaldii
      fonts:
        - asset: assets/fonts/Vivaldii.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
